function onhome(){
                 window.location.href=("index.html");
                }               


function onproduct(){
                    window.location.href=("product.html");
                
                }

 function onabout(){
                 window.location.href=("about.html");
                }
 function oncontact(){
                 window.location.href=("contact.html");
                }               